### ISSUE TITLE
Feedback for “Tutorials and Guides” - After generating "books" getting "No QueryClient set, use QueryClientProvider to set one" 

### ISSUE THREAD

**Issue by companyofwords** [nicoalbanese/kirimase-docs#1]
Hi,  great job on a brilliant idea for CLI. 

I have just followed your longer video and spun up Kirimase with additional "books" model, ui and trpc route as on your video, but when i go to "books" it is telling me "No QueryClient set, use QueryClientProvider to set one".  Just thought would flag up. 

Thanks

**Comment by nicoalbanese** [comment]
Hey @companyofwords  - thanks for flagging. I've just reproduced and I think it has something to do with React Query going to V5 recently. I'm looking into a fix

**Comment by nicoalbanese** [comment]
Ok - it's definitely an issue with the trpc related packages.

I've downgrade the following:
```
    "@trpc/client": "10.37.1",
    "@trpc/next": "10.37.1",
    "@trpc/react-query": "10.37.1",
    "@trpc/server": "10.37.1",
```
and it resolves the problem. You can do this on your existing project by replacing the entries with the above and then running `bun update` or whatever package manager youre using. You can also run the following which will achieve the same result: `bun add @trpc/client@10.37.1 @trpc/react-query@10.37.1 @trpc/server@10.37.1 @trpc/next@10.37.1`

I've also updated the CLI (v0.0.25) if you want to just start again. Let me know if that resolves things. Cheers!

**Comment by companyofwords** [comment]
Thanks. Did it resolve for you please? Still issue for me - comparing it with similar trpc projects....it's nextjs 14 btw....

**Comment by nicoalbanese** [comment]
Yes - it resolved it for me. Have you tried deleting your node_modules and then running your install command again with the updated package.json mentioned above?

**Comment by nicoalbanese** [comment]
Nevermind - still running into issues.

**Comment by nicoalbanese** [comment]
Ok - this has been mighty tricky to debug. I've figured out that it's definitely coming from React Query ^5.0.0 and above. Not sure what they've changed and how to resolve it yet, but for the meantime you can do the following:

1. Update your package JSON entry for react query to the following:
`"@tanstack/react-query": "^4.32.6",`
2. Delete your package managers lock file (for me `bun.lockb`) and `node_modules`
3. run your package managers' install command (for me `bun install`) and then if you're using prisma generate the prisma client

In the meantime, I'll be looking into why this is happening

**Comment by nicoalbanese** [comment]
Ok - confirmed is an issue with react query and the trpc will be incorporating support coming in upcoming v.11. If you want to use react-query v5 you can use the `@next` packages for trpc and it will work. I would suggest just downgrading react-query for now though. Cheers!

**Comment by nicoalbanese** [comment]
fyi - here is the thread from the trpc repo: https://github.com/trpc/trpc/issues/4218
